// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYr5Ao4gXBJUReIBLxvJBim6fGPJkD4p0',
    appId: '1:602575644560:web:c2b259ecca6000c2fdf515',
    messagingSenderId: '602575644560',
    projectId: 'expense-tracker-5d7ef',
    authDomain: 'expense-tracker-5d7ef.firebaseapp.com',
    storageBucket: 'expense-tracker-5d7ef.firebasestorage.app',
    measurementId: 'G-7F1L5S189T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWOZy_IrwWLmxZa2LOwZpJfSSjmdrNfkM',
    appId: '1:602575644560:android:ab4fe565637c9232fdf515',
    messagingSenderId: '602575644560',
    projectId: 'expense-tracker-5d7ef',
    storageBucket: 'expense-tracker-5d7ef.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0HVOt5Vyo_djlRF7i3tr6KGO1f5hDBW0',
    appId: '1:602575644560:ios:2ac701a9174a4613fdf515',
    messagingSenderId: '602575644560',
    projectId: 'expense-tracker-5d7ef',
    storageBucket: 'expense-tracker-5d7ef.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0HVOt5Vyo_djlRF7i3tr6KGO1f5hDBW0',
    appId: '1:602575644560:ios:2ac701a9174a4613fdf515',
    messagingSenderId: '602575644560',
    projectId: 'expense-tracker-5d7ef',
    storageBucket: 'expense-tracker-5d7ef.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );
}
